networks:
  k6:
  grafana:

services:
  k6:
    image: grafana/k6:latest
    container_name: k6-container
    volumes:
      - ./tests:/scripts # Mount your local k6 scripts directory
    ports:
      - "6565:6565"
    entrypoint: ["sh", "/scripts/wait.sh", "price-api", "80","--", "k6", "run", "/scripts/load-search.js" ]
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    networks:
      - k6
  price-api:
    container_name: price-api
    privileged: true
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ./loadtesting.Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=loadtesting
    ports:
      - "80:80"
    networks:
      - k6
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    networks:
      - k6

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUX_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml