name: Build

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout working directory
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check build


      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          annotate_only: true # actions were being sent to the wrong workflow: https://github.com/mikepenz/action-junit-report/issues/40
          detailed_summary: true
          include_passed: false

